site_name: Facilitating Responsible Participation in Data Science
site_url: https://facilitating-responsible-participation.netlify.app
repo_url: https://github.com/alan-turing-institute/responsible-participation
repo_name: alan-turing-institute/responsible-participation
theme:
  name: material
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences